Run debricked scan
RaaLabs/Connectors.Kyma pull request #10
Opened 2022-11-28 12:22 UTC by rafaelschlatter

## Summary

Summary of the PR here. The GitHub release description is created from this comment so keep it nice and descriptive.

Remember to remove sections that you don't need or use.

### Added

- Describe the added features

### Changed

- Describe the outwards facing code change

### Fixed

- Describe the fix and the bug

### Removed

- Describe what was removed and why

### Security

- Describe the security issue and the fix

### Deprecated

- Describe the part of the code being deprecated and why

2022-11-29 22:42 UTC, srudaa requested changes
Fix the namespace for IMetricsHandler and all modules using this one.

2022-11-29 22:42 UTC, srudaa commented on Source/Metrics/IMetricsHandler.cs
> +namespace RaaLabs.Edge.Connectors.Modbus.Metrics;
Fix namespace

2022-11-30 06:59 UTC, rafaelschlatter commented on Source/Metrics/IMetricsHandler.cs
> +namespace RaaLabs.Edge.Connectors.Modbus.Metrics;
Fixed, wonder how this was able to build ...

2022-11-30 08:32 UTC, katarinagud approved these changes

2022-11-30 12:15 UTC, merged